FROM golang:1.19

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY * ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /greeter-server ./greeter_server/main.go

# Run
CMD ["/greeter-client"]
